name: nutsnbolts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^5.0.2
  dash_chat_2: ^0.0.21
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  swipe_cards: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/nnb.jpeg'
